### ISSUE TITLE
Import types

### ISSUE THREAD

**Issue by wrdls** [pulumi/pulumi-aiven#113]
I want to import existing Aiven resources with `pulumi import` but I can't figure out how to do it. 
The [Terraform provider](https://registry.terraform.io/providers/aiven/aiven/latest/docs#importing-existing-infrastructure) support importing, so I'd assume Pulumi can support it as well.

I asked in the [Pulumi Community Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1614624612374700) and user `jaxxstorm` told me it was possible but the "docs might not have generated the import types".

Can this be fixed?

**Comment by wrdls** [comment]
Any update on this? It's been 2.5 months for something seemingly trivial?

**Comment by AmitaiMazliah** [comment]
also waiting for this

**Comment by AaronFriel** [comment]
Hey folks, apologies for the delay on responding to this issue. This should be fixed on all resources in the provider, at the bottom of the Pulumi Registry docs you should find an example import command, for example: https://www.pulumi.com/registry/packages/aiven/api-docs/clickhouse/#import

If there is a resource we're not generating this for, please create a new issue for our team to track!
