### ISSUE TITLE
kafkaUserConfig.kafka.logCleanerMinCleanableRatio being cast to 0

### ISSUE THREAD

**Issue by alexhwoods** [pulumi/pulumi-aiven#127]
First of all, thank you guys for your awesome work on this project! We're super grateful for the Pulumi team 😃 
___

When upgrading from `@pulumi/aiven` 3.5.1 to 3.6.1, the value `kafkaUserConfig.kafka.logCleanerMinCleanableRatio` has a new default value — 0. Which is an invalid value.

The field means "if 50% of the log has already been compacted, don't allow the log cleaner to compact any more". So, "if none of the log has already been compacted, don't allow the log cleaner to compact any more" -> "so never compact" (when compaction is selected as the cleanup policy).

Furthermore, the Aiven API rejects the value of 0. You get this error message
```
{
  "errors": [
    {
      "message": "Invalid user_config: Invalid input for kafka: 0 is less than the minimum of 0.2",
      "status": 400
    }
  ],
  "message": "Invalid user_config: Invalid input for kafka: 0 is less than the minimum of 0.2"
}
```

## Expected behavior
The default value should be 0.5, [like in Kafka itself](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_min.cleanable.dirty.ratio). I'd argue 0 is an invalid value, but I could be wrong there.

## Current behavior
Match Kafka's default value of 0.5.

## Steps to reproduce

1. Create an `aiven.Service` of `serviceType: 'kafka'`, with `@pulumi/aiven: 3.5.1`. Don't specify `kafkaUserConfig.kafka.logCleanerMinCleanableRatio`.
2. Upgrade to `@pulumi/aiven: 3.6.1`

Note that you can then see the code work if you do specify the value, at `0.5`.

## Context (Environment)
I want to upgrade to the newest version :)

## Affected feature
`aiven.Service` of `serviceType: 'kafka'`. This is also not a huge deal, because there's a workaround. (specify the value of `0.5` for `kafkaUserConfig.kafka.logCleanerMinCleanableRatio`).

**Comment by iwahbe** [comment]
The `aiven.Service` resource no longer exists. It has been moved into a couple of types (mainly `aiven.ServiceIntegration`). If you are still experiencing a similar issue, please confirm the issue still exists on latest (6.24.1), and open a new issue.
