### ISSUE TITLE
AIVEN_API_TOKEN environment variable not recognised under Python

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aiven#135]
## Expected behavior

The documentation says that we can configure the Aiven token by setting up the environment variable `AIVEN_API_TOKEN`. This is not working for Python projects. I haven't tried other languages.

## Current behavior

Pulumi complains:

```
    error: 1 error occurred:
        * missing required configuration key "aiven:apiToken": Aiven Authentication Token
    Set a value using the command `pulumi config set aiven:apiToken <value>`.
```

## Steps to reproduce

Set up `AIVEN_API_TOKEN` environment variable and try to create any Aiven resource. For example:

```
aiven.Account("dev",
              name="Dev",
              tenant_id="timescale")
```

## Context (Environment)

A potential caveat here is that I'm running the Aiven provider against Timescale Cloud, which uses Aiven underneath. Having said that, this workaround works:

```
provider = aiven.Provider("dev",
                          api_token=os.environ['AIVEN_API_TOKEN'])

aiven.Account("dev",
              name="Dev",
              tenant_id="timescale",
              opts=pulumi.ResourceOptions(provider=provider))
```

This proves that the environment variable is set up correctly, but being ignored by pulumi-aiven.

**Comment by stack72** [comment]
Hi @Sodki 

It's actually "AIVEN_TOKEN" not "AIVEN_API_TOKEN"

That's actually a mistake in our README and config that I will fix first thing in the morning

I'm sorry about that :/

Paul
