### ISSUE TITLE
Unable to use function GetAccountTeam, error in "account_id"

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aiven#143]
When using the function GetAccountTeam, I get the following error:

```
    TypeError: get_account_team() got multiple values for argument 'account_id'
```

## Steps to reproduce

```
# Create an account
account = aiven.Account("test",
                        name="test",
                        tenant_id="timescale")

# Create a team, this finishes successfully
aiven.AccountTeam("developers",
                  account_id=account.account_id,
                  name="Developers")

# Get a team, this fails
aiven.get_account_team("owners",
                       account_id=account.account_id,
                       name="Account Owners")
```

I also tried to use a string with the correct value and I get the same error.

**Comment by emiliza** [comment]
@Sodki can you try removing `"owners"` from `get_account_team`?

https://www.pulumi.com/docs/reference/pkg/aiven/getaccountteam/#using first input param is account_id which you're later setting, so it appears the error you're getting back is actually intended. Let me know if this helps solve your problem

**Comment by Sodki** [comment]
Oh you're absolutely right @emiliza! I'm so used to having resource names everywhere that I overlooked this documentation detail. Thank you!
