### ISSUE TITLE
Resources not cleaned up from test, incurring ongoing charges in Aiven account

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-aiven#235]
- [x] Suspend tests
- [x] Document account (likely bot@pulumi.com) used: answer - in engineering team 1password vault.
- [x] Clean up outstanding resources in account
- [ ] Follow up with @isaac-pulumi on approach to re-enable tests or future steps.

**Comment by AaronFriel** [comment]
Removing P1 and keeping this as a tracking issue.

**Comment by guineveresaenger** [comment]
I recommend a cleaner-upper, which has been used as a solution in other providers: https://github.com/pulumi/civo-account-cleanup

**Comment by t0yv0** [comment]
Also https://github.com/pulumi/ci-mgmt/pull/379 perhaps relevant.

I don't mind keeping this open, just FYI more tests are running now in Aiven that were skipped before today. Just in case this causes further problems.

**Comment by AaronFriel** [comment]
In the case of this issue, the cleanup failed due to provider timeouts. The physical resource creation succeeded async after the provider timed out, and logical resource create call failed. The state file thus had no resources to clean up when programtest ran `pulumi destroy`.

**Comment by iwahbe** [comment]
Tests are no longer suspended.

**Comment by mjeffryes** [comment]
Looks like we had another resource leak. I'm going to disable tests again.
