### ISSUE TITLE
Remove the CustomizeDiff patch when underlying issues are fixed

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aiven#273]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/pulumi/pulumi-terraform-bridge/issues/911 caused aiven provider to panic in Pulumi, and is being worked around by patching upstream. Once the problem is solved correctly, we should remove the patch.

**Comment by iwahbe** [comment]
Fixed by https://github.com/pulumi/pulumi-aiven/pull/728.
