### ISSUE TITLE
Debug message related to kafkaTopicCache keeps appearing even though I don't use it

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-aiven#339]
### What happened?

Whenever I use any Aiven resource, I get the following message on the `Diagnostics:` part of my Pulumi run:

```
    2023/07/14 12:15:31 [DEBUG] Creating an instance of kafkaTopicCache ...
```

I'm using Pulumi with Python.

### Expected Behavior

I'm not using any Kafka resources, so that message shouldn't appear.

### Steps to reproduce

The following Python code is enough to trigger the message:

```
import pulumi_aiven
pulumi_aiven.Organization("organization")
```

And then just run a `pulumi pre`.

### Output of `pulumi about`

```
CLI
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
aiven         6.4.0
python        unknown

Host
OS	 fedora
Version  38
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.4'

Current Stack: test   

Dependencies:
NAME                 VERSION
pip                  23.1.2
psycopg2-binary      2.9.5
pulumi-aiven         6.4.0
rsa                  4.9.0
setuptools           68.0.0
wheel                0.40.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @Sodki. Thanks for bringing this to our attention. The aiven provider [creates](https://github.com/aiven/terraform-provider-aiven/blob/e5d0f2793c3f587a1e1ae0b1b1ff5ac7b28cc0f1/internal/sdkprovider/service/kafka/kafka_topic.go#L224-L225) the [cache](https://github.com/aiven/terraform-provider-aiven/blob/e5d0f2793c3f587a1e1ae0b1b1ff5ac7b28cc0f1/internal/sdkprovider/service/kafka/kafka_topic_cache.go#L23-L25) as part of setting up the provider, even if no kafka resources are created. This is working as expected. *However*, always showing debug logs is not helpful.

We can trivially repro with the following program (and no credentials):


```yaml
name: repro
runtime: yaml
resources:
  app:
    type: pulumi:providers:aiven
    properties:
      apiToken: ""
```

I have created https://github.com/pulumi/pulumi-terraform-bridge/issues/1298 to track a fix in pulumi-terraform-bridge.

**Comment by iwahbe** [comment]
This no longer repros, so I'm closing the issue.
