### ISSUE TITLE
Thanos resource and data source are missing

### ISSUE THREAD

**Issue by supergillis** [pulumi/pulumi-aiven#677]
### Describe what happened

The Thanos resource and datasource are not in the Pulumi provider. They are in the Terraform provider.

### Sample program

N/A

### Output of `pulumi about`

```
CLI          
Version      3.123.0
Go Version   go1.22.5
Go Compiler  gc

Host     
OS       arch
Version  
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @supergillis. It looks like those resources are restricted to beta:

https://github.com/aiven/terraform-provider-aiven/blob/11f14ea68b324d274bc5ad399f5e5c35221761bb/internal/sdkprovider/provider/provider.go#L262-L271

We don't currently enable beta features for this provider.
